CREATE TABLE IF NOT EXISTS public.usuario
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    apellidos character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nickname character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(30) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    rol character varying(255) COLLATE pg_catalog."default" NOT NULL,
    token integer NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email),
    CONSTRAINT uklbkxel95iw6vtu2w6huyrpu26 UNIQUE (nickname),
    CONSTRAINT usuario_rol_check CHECK (rol::text = ANY (ARRAY['ADMIN'::character varying, 'USUARIO'::character varying]::text[]))
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.usuario
    OWNER to admin;


INSERT INTO public.usuario(
    apellidos, email, nickname, nombre, password, rol, token)
VALUES ('Apellido 1', 'pepe@pepe.com', 'pepe', 'pepe',
        '$2a$10$w5ewfdBtL87AMoMk7MGJm.qWma.swNh.oxQCiGkQalRGz7rebnLae',
        'USUARIO', 57);
INSERT INTO public.usuario(
    apellidos, email, nickname, nombre, password, rol, token)
VALUES ('Admin 1', 'admin@admin.com', 'admin', 'admin',
        '$2a$10$w5ewfdBtL87AMoMk7MGJm.qWma.swNh.oxQCiGkQalRGz7rebnLae',
        'ADMIN', 77);